
import com.sun.corba.se.spi.activation.Server;
import java.awt.Color;
import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sidiq
 */
public class Client_server extends javax.swing.JFrame implements Runnable{

    protected String ip;
    protected String local_name;
    protected String remote_name;
    protected Socket s1;
    protected ServerSocket s;
    protected BufferedReader br;
    protected BufferedWriter bw;
    protected Thread th;
    protected String a;
    boolean cek = true;
    
    public Client_server() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_CONNECTT = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        Btn_SEND = new javax.swing.JButton();
        list = new java.awt.List();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        TextField_Nama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFiel_IP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Btn_XIT = new javax.swing.JButton();
        btn_status = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_CONNECTT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_CONNECTT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connectoke.png"))); // NOI18N
        Btn_CONNECTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CONNECTTActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_CONNECTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 158, 73));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Server", "Client" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 162, 43));

        Btn_SEND.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_SEND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mail,oke.png"))); // NOI18N
        Btn_SEND.setEnabled(false);
        Btn_SEND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SENDActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_SEND, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 109, 73));
        getContentPane().add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 250, 228));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 250, 73));

        TextField_Nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(TextField_Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 162, 41));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ip Address");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        textFiel_IP.setEditable(false);
        textFiel_IP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textFiel_IP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFiel_IPActionPerformed(evt);
            }
        });
        getContentPane().add(textFiel_IP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 160, 43));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Pilih Sebagai");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        Btn_XIT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btn_XIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit copy.png"))); // NOI18N
        Btn_XIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XITActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_XIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 158, 73));

        btn_status.setBackground(new java.awt.Color(255, 0, 51));
        btn_status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_status.setText("OFF");
        getContentPane().add(btn_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 162, 39));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Ku");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Chatting Client-Server");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("49012056");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Israq Luthfan Sidiq");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("STEI - TMD");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Institute Teknologi Bandung");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CONNECTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CONNECTTActionPerformed
        
        String opsi = (String) jComboBox1.getSelectedItem();

        if (jComboBox1.getSelectedIndex() == 0) {
            server_jalan();
            Btn_CONNECTT.setVisible(false);
            
        } else {
            client_jalan();
             Btn_CONNECTT.setVisible(false);
             
        } 
         
    }//GEN-LAST:event_Btn_CONNECTTActionPerformed

    private void textFiel_IPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFiel_IPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFiel_IPActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0){
        textFiel_IP.setEditable(false);
        }
        else {
        textFiel_IP.setEditable(true);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void Btn_SENDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SENDActionPerformed
       
        try {
            // TODO add your handling code here:
            local_name= TextField_Nama.getText();
            bw.write(local_name + ":  " + jTextArea1.getText());
            bw.newLine(); 
            bw.flush();
            list.addItem(local_name + ": " + jTextArea1.getText());
            jTextArea1.setText("");
        
            
            
        } catch (IOException ex) {
            Logger.getLogger(Client_server.class.getName()).log(Level.SEVERE, null, ex);
        
        }
    }//GEN-LAST:event_Btn_SENDActionPerformed

    private void Btn_XITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XITActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_XITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Client_server().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_CONNECTT;
    private javax.swing.JButton Btn_SEND;
    private javax.swing.JButton Btn_XIT;
    private javax.swing.JTextField TextField_Nama;
    private javax.swing.JButton btn_status;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.List list;
    private javax.swing.JTextField textFiel_IP;
    // End of variables declaration//GEN-END:variables

    private void server_jalan() {

        
        while (cek) {
            try {
                s = new ServerSocket(100);
                this.setTitle("Menunggu...");
                s1 = s.accept();
                this.setTitle("Konek...!!");
                Btn_SEND.setEnabled(true);
                btn_status.setBackground(Color.GREEN);
                btn_status.setText("ON");
                
                list.addItem("Terhubung dengan Client");
                br = new BufferedReader(new InputStreamReader(
                        s1.getInputStream()));
                bw = new BufferedWriter(new OutputStreamWriter(
                        s1.getOutputStream()));
                Thread th;
                th = new Thread(this);
                this.setTitle("Terkoneksi");
               // bw.newLine();
                th.start();
                cek = false;
                
            } catch (Exception ex) {
                
                this.setTitle("Menunggu Client...");
                
                
                
            }
        }
    }

    @Override
    public void run() {
        while (true) {
            try {
                list.addItem(br.readLine());
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    private void client_jalan() {
        
        while (cek){
        try {
            ip=textFiel_IP.getText();
            s1 = new Socket(ip, 100);
            this.setTitle("Konek...!!");
            ///Btn_oke.setText("DISCONNECT");
            Btn_SEND.setEnabled(true);
            btn_status.setBackground(Color.GREEN);
            btn_status.setText("ON");
          
            list.addItem("Terhubung dengan Server");
            br = new BufferedReader(new InputStreamReader(
                    s1.getInputStream())); // untuk mengambil input stream
            bw = new BufferedWriter(new OutputStreamWriter(
                    s1.getOutputStream())); // utk mengirim stream

            Thread th;
            th = new Thread(this);
            // bw.newLine();
            th.start();
            cek = false;
            
        } catch (Exception e) {
            list.addItem("Mencari Server");
            try {
                    Thread.sleep(1000);
                } catch (Exception g) {
                }
            }
      
        }
    
    }
}
    

